version: '3'
services:
  mongodb:
    container_name: mongo-container
    image: mongo:8
    ports:
      - '27017:27017'
    volumes:
      - ./mongodbvolume:/data/db
    networks:
      - postgres



